// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import PagyController from "./pagy_controller"
application.register("pagy", PagyController)

import RateController from "./rate_controller"
application.register("rate", RateController)
