AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'bin/bundle'    

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  
Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Max: 9

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10
